//
//  AccessTokenAdapter.swift
//  TDDChatProject
//
//  Created by Mendy Edri on 31/12/2019.
//  Copyright © 2019 CWT. All rights reserved.
//

import Foundation

public protocol AccessTokenAdapter {
    func requestAccessToken(_ completion: (Result<String, Error>) -> Void)
}

internal struct AccessTokenTempAdapter: AccessTokenAdapter {
    func requestAccessToken(_ completion: (Result<String, Error>) -> Void) {
        completion(.success("eyJhbGciOiJSUzUxMiIsImtpZCI6InRva2VuQ2VydCJ9.eyJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIl0sImNsaWVudF9pZCI6IkN3dFRvR29PYXV0aENsaWVudCIsImp3dE9BdXRoIjoia1BXQzN0YXo2Q2IzbEhkcEpEZkJWc0M1TmZ1WHZNVDUiLCJpZG1FbWFpbCI6ImRlQHlvcG1haWwuY29tIiwibGFzdE5hbWUiOiJJRE0iLCJ0b3BJZCI6IjE0OjRhYjczIiwicm9sZXMiOiJ0cmF2ZWxlciIsInRyYXZlbGVyRW1haWwiOiJkZUB5b3BtYWlsLmNvbSIsInRyYXZlbGVyVHlwZUdVSUQiOiIxNDo0MWMzNSIsInN1YklkIjoiMTQ6YzU0NTAiLCJmaXJzdE5hbWUiOiJERSIsIm1pZGRsZU5hbWUiOiJ0ZWFzdCIsImlkIjoiNzc3YWUwOGItNmE2Yi00MmU5LTkwNjgtMzE0ZGUwNGJjOTgyIiwidHJhdmVsZXJHVUlEIjoiMTQ6MjU5Nzc5OGUiLCJ1c2VybmFtZSI6ImRlQHlvcG1haWwuY29tIiwiZXhwIjoxNTc3ODg2OTUzfQ.JfXotZ8WLNU8ym5fMUOzwRteORKVlBcu5rHXF1mTQltPA7HZh4V1byesIKJV4ccNq2wZrOoRhsf-K9zjS5IUDteII38aKDXP5nm2Y7lflvCZgkphalf76kOzi1HXjSu7rgTV2_1T4N8jg0mYHlfxUsxhnSIL5AL9rPVqZXFgtl6khCIAXIBbzbpl1xAb5T4BAqWcK2thzP2GDpMfQlmNten6D3XmOfB0xo6CxInwf6bavky4cU_qB9e_TRBXgr5hIak5C649favs8mFU-03DHI_D0556H_LCuA1kCBAR6Qcu2Y5nd9jhI73fFhJQxvyUzSzMEqh8aCpDTzKwqkgsCA"))
    }
}
