//
//  AccessTokenAdapter.swift
//  TDDChatProject
//
//  Created by Mendy Edri on 31/12/2019.
//  Copyright © 2019 CWT. All rights reserved.
//

import Foundation

public protocol AccessTokenAdapter {
    func requestAccessToken(_ completion: (Result<String, Error>) -> Void)
}

internal struct AccessTokenTempAdapter: AccessTokenAdapter {
    func requestAccessToken(_ completion: (Result<String, Error>) -> Void) {
        completion(.success("eyJhbGciOiJSUzUxMiIsImtpZCI6InRva2VuQ2VydCJ9.eyJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIl0sImNsaWVudF9pZCI6IkN3dFRvR29PYXV0aENsaWVudCIsImp3dE9BdXRoIjoidnpjSU5QWUlWbGxzRkdzellRT2Z6ekE4NDhXbUhVNXAiLCJpZG1FbWFpbCI6ImRlQHlvcG1haWwuY29tIiwibGFzdE5hbWUiOiJJRE0iLCJ0b3BJZCI6IjE0OjRhYjczIiwicm9sZXMiOiJ0cmF2ZWxlciIsInRyYXZlbGVyRW1haWwiOiJkZUB5b3BtYWlsLmNvbSIsInRyYXZlbGVyVHlwZUdVSUQiOiIxNDo0MWMzNSIsInN1YklkIjoiMTQ6YzU0NTAiLCJmaXJzdE5hbWUiOiJERSIsIm1pZGRsZU5hbWUiOiJ0ZWFzdCIsImlkIjoiNzc3YWUwOGItNmE2Yi00MmU5LTkwNjgtMzE0ZGUwNGJjOTgyIiwidHJhdmVsZXJHVUlEIjoiMTQ6MjU5Nzc5OGUiLCJ1c2VybmFtZSI6ImRlQHlvcG1haWwuY29tIiwiZXhwIjoxNTc3ODc0ODA2fQ.cP1rwo65doRi6F7z2JdbwtttgkDEX37dQLzRSn06uuf6DWfjMdMHS9L0qyJjX8SInHMxG8kGtmYbXRmmPI00ZIhJZwHrD4Dwk3wNwU1clL-FgMzMyGbbNwMdb-AmQBUtprGa_-fN-T6xEWTV9bXaziCIiBN5heVkYCETj6Mub67k74NkuEhtT22CM4m0nSpQBS45nlHRdI0LD8Ifln6qB6JKB5Icm44GLGxQ66MzAXdFZY5NJ50G16ALrh48DaI2nusmmfFCkUHhELvC7Vn8_2SISvt6kb8MxU7-i6Sl02WVmh4kcRc4YnT8LurZqtiYd0-fxdX2rOCQ3iaNq_tTjg"))
    }
}
