//
//  AccessTokenTempAdapter.swift
//  TDDChatProject
//
//  Created by Mendy Edri on 14/01/2020.
//  Copyright © 2020 CWT. All rights reserved.
//

import Foundation
import lit_networking

class AccessTokenTempAdapter: AccessTokenAdapter {
    func requestAccessToken(_ completion: (Result<String, Error>) -> Void) {
        completion(.success("eyJhbGciOiJSUzUxMiIsImtpZCI6InRva2VuQ2VydCJ9.eyJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIl0sImNsaWVudF9pZCI6IkN3dFRvR29PYXV0aENsaWVudCIsImp3dE9BdXRoIjoieXdnMjExMVRwU0xmREFvNGN5eHBpRk95TDVqZGE0blIiLCJpZG1FbWFpbCI6ImRlQHlvcG1haWwuY29tIiwibGFzdE5hbWUiOiJJRE0iLCJ0b3BJZCI6IjE0OjRhYjczIiwicm9sZXMiOiJ0cmF2ZWxlciIsInRyYXZlbGVyRW1haWwiOiJkZUB5b3BtYWlsLmNvbSIsInRyYXZlbGVyVHlwZUdVSUQiOiIxNDo0MWMzNSIsInN1YklkIjoiMTQ6YzU0NTAiLCJmaXJzdE5hbWUiOiJERSIsIm1pZGRsZU5hbWUiOiJ0ZWFzdCIsImlkIjoiNzc3YWUwOGItNmE2Yi00MmU5LTkwNjgtMzE0ZGUwNGJjOTgyIiwidHJhdmVsZXJHVUlEIjoiMTQ6MjU5Nzc5OGUiLCJ1c2VybmFtZSI6ImRlQHlvcG1haWwuY29tIiwiZXhwIjoxNTc5NjgzODA5fQ.QvI1DF-f6Z4aQt5D0gzfkbYmZ0V9bSfjADQ0KQkQOVTrQT2PZa7UyBOjiZZloof2CIxaYdt2Oo7Rd9Do6PkFkpanJpWFWGweCAgR5LC6ixaZ2zBeCB_by8XzesVnASHhScPA8g4SnZOaWHzZOPHXR6hyYxCymUl-j29ht5xHBfNLA9sTDh3mzUYBY5Ceck4x0YrcrHgT8s4m1R-WQlwckihaQvHdPFvA6gogMgtnUiqQ1UiPPHqZZG_Yhpj-v9536kEZbNl_YkdfpgEQfMG7mZWfMbT0FjaBMb5KLKdzETt9Px02_C15ahfr0XZ9jSFi1zyI9rhiggPng-TYJb5PIw"))
    }
}
