//
//  AccessTokenTempAdapter.swift
//  TDDChatProject
//
//  Created by Mendy Edri on 14/01/2020.
//  Copyright © 2020 CWT. All rights reserved.
//

import Foundation
import lit_networking

class AccessTokenTempAdapter: AccessTokenAdapter {
    func requestAccessToken(_ completion: (Result<String, Error>) -> Void) {
        completion(.success("eyJhbGciOiJSUzUxMiIsImtpZCI6InRva2VuQ2VydCJ9.eyJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIl0sImNsaWVudF9pZCI6IkN3dFRvR29PYXV0aENsaWVudCIsImp3dE9BdXRoIjoiNWdzOFVwOEdPRUhtd2hjZWJNbjlja2ttcWVmZnExZGsiLCJpZG1FbWFpbCI6ImRlQHlvcG1haWwuY29tIiwibGFzdE5hbWUiOiJJRE0iLCJ0b3BJZCI6IjE0OjRhYjczIiwicm9sZXMiOiJ0cmF2ZWxlciIsInRyYXZlbGVyRW1haWwiOiJkZUB5b3BtYWlsLmNvbSIsInRyYXZlbGVyVHlwZUdVSUQiOiIxNDo0MWMzNSIsInN1YklkIjoiMTQ6YzU0NTAiLCJmaXJzdE5hbWUiOiJERSIsIm1pZGRsZU5hbWUiOiJ0ZWFzdCIsImlkIjoiNzc3YWUwOGItNmE2Yi00MmU5LTkwNjgtMzE0ZGUwNGJjOTgyIiwidHJhdmVsZXJHVUlEIjoiMTQ6MjU5Nzc5OGUiLCJ1c2VybmFtZSI6ImRlQHlvcG1haWwuY29tIiwiZXhwIjoxNTc5NjkyNTk2fQ.V-AUeeDgSXzW9Wy2NrRR0plC5vzymWgFEdYfrrmpimAI0OgEmZxJmYrOInynKC7iKdj4NNfziV9xsIJmTtqxfzafaSvwOFo8KDZEK0sfgu7I-OqCE8-d1dVpaBkeiwC9Lg_CcYhgTAskRdsq9NPtdFKArlwWL1JTKTBQ4SZCn7WmklFrn6ff2qaw3lY3kRk7uPfLfXY4nGdoIauYQ3fMknCDCDdeT_Ik3yJsspiS15L5_AUs2eDSxi1u4XQixR4hT0PlEdCUnsHkoCwwDMJAnCS_mbR656c-S2t3IjkjcoM36PJMwc9skz-9qGYg80wgDGJa-ptnjBh-MkQqB0sZzw"))
    }
}
